language: python
python:
- 2.7
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -SLk https://www.abisource.com/downloads/enchant/1.6.0/enchant-1.6.0.tar.gz | tar xvz
- cd enchant-1.6.0
- ./configure --prefix=`pwd`
- make install
- cd ..
install:
- git clone https://github.com/plone/papyrus ../papyrus && cd ../papyrus
- virtualenv . && source bin/activate
- mkdir -p source && ln -s ../../documentation source/documentation
- pip install zc.buildout
- bin/buildout -N -t 3 buildout:eggs-directory=../eggs buildout:checkout=documentation sources:documentation="git https://github.com/plone/documentation egg=false" versions:plone.app.robotframework=0.9.14
before_script:
- echo '[general]' > docutils.conf
- echo 'report_level = 5' >> docutils.conf
script:
- LANGS=en make html
after_script:
cache:
  directories:
  - ../eggs
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-docs
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
#   - ! 'Sphinx: http://plone-documentation.s3-website-us-east-1.amazonaws.com/artifacts/%{build_number}/%{build_number}.1/en/'
env:
  global:
  - LD_LIBRARY_PATH=`pwd`/enchant-1.6.0/lib
