language: python
python:
- 2.7
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -O http://www.abisource.com/downloads/enchant/1.6.0/enchant-1.6.0.tar.gz
- tar xzvf enchant-1.6.0.tar.gz
- cd enchant-1.6.0
- ./configure --prefix=`pwd`
- make install
- cd ..
install:
- git clone https://github.com/plone/papyrus ../papyrus && cd ../papyrus
- python bootstrap-buildout.py --setuptools-version=18.0.1 --version=2.4.0
- bin/buildout -N -t 3 buildout:eggs-directory=../eggs buildout:checkout=documentation sources:documentation="git https://github.com/plone/documentation egg=false" versions:plone.app.robotframework=0.9.14
before_script:
- echo '[general]' > docutils.conf
- echo 'report_level = 5' >> docutils.conf
- rm -rf source/documentation/external/plone.app.robotframework
script:
- bin/pybot --listener plone.app.robotframework.server.LazyStop source
- LANGS=en make html SPHINXOPTS="-D sphinxcontrib_robotframework_enabled=0"
after_script:
cache:
  directories:
  - ../eggs
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-docs
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
#   - ! 'Sphinx: http://plone-documentation.s3-website-us-east-1.amazonaws.com/artifacts/%{build_number}/%{build_number}.1/en/'
env:
  global:
  - LD_LIBRARY_PATH=`pwd`/enchant-1.6.0/lib
