language: python
python: '2.7'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- git clone https://github.com/plone/papyrus ../papyrus && cd ../papyrus
- mkdir -p source && ln -s ../../documentation source/documentation
- mkdir -p buildout-cache/downloads
- virtualenv buildout
- buildout/bin/python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg buildout:checkout=documentation sources:documentation="fs
  documentation egg=false"
before_script:
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
script:
- LANGS=en make html
after_script:
- travis-artifacts upload --path build/html
- travis-artifacts upload --target-path latest --path build/html
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-docs
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
    - ! 'Sphinx: http://plone-documentation.s3-website-us-east-1.amazonaws.com/artifacts/%{build_number}/%{build_number}.1/en/'
env:
  global:
  - ARTIFACTS_S3_BUCKET=plone-documentation
  - secure: B1NL93YgevEmUmvogdnq6Cz1GFvsFiYyCIv6yvudss2f9jzX1nzolbXiH8bFDwJnNQmkzFSm+fzWRDCSvoO8KnvLHTOjsrlcLQ6Er9A/vNQU1DgBvoqxBI7Y+h8OrTzhGK7YENAD/1PkSXmt/OAji/YKJNSULTawpGN1hGBfEio=
  - secure: Bn6H7ckcLTZrR73FcoqWH2ukzlQKGyDyFFAPN9FbJ0/gPH3a/6XLMe59WH6pYcvzxotxfvaQEloTuXnJvjn/f7lTkRHU1Z+DbymdmXuhNCv0meMwg0EhSKiqfYpUqhs/1Jn/fqUnxcFu66Ts905DKs1fnBbWHG5+JmVkslFaRSo=
